name: Terraform Destroy (one-off)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: Type DESTROY to confirm
        required: true
      workspace:
        description: Terraform workspace to destroy (default: default)
        required: false
        default: default
      tf_version:
        description: Terraform version to use (default: 1.13.1)
        required: false
        default: 1.13.1
      parallelism:
        description: terraform destroy parallelism (default: 1)
        required: false
        default: "1"

env:
  AWS_REGION: us-east-1

jobs:
  destroy:
    if: github.event.inputs.confirm == 'DESTROY'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ github.event.inputs.tf_version }}
          terraform_wrapper: false

      - name: Terraform init (use backend from code)
        run: terraform init -reconfigure

      - name: Select workspace
        run: |
          WS="${{ github.event.inputs.workspace }}"
          terraform workspace list
          terraform workspace select "$WS" || terraform workspace new "$WS"
          echo "Using workspace: $(terraform workspace show)"

      - name: Plan destroy
        run: terraform plan -destroy -no-color -input=false -out=destroy.tfplan

      - name: Apply destroy
        run: terraform apply -input=false -auto-approve -parallelism=${{ github.event.inputs.parallelism }} destroy.tfplan

      - name: Show remaining state
        run: terraform state list || echo "No resources left in state."
