name: Terraform Destroy (one-off)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type DESTROY to confirm"
        required: true
        default: ""

env:
  AWS_REGION: us-east-1

jobs:
  destroy:
    if: ${{ github.event.inputs.confirm == 'DESTROY' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1
          terraform_wrapper: false

      - name: Terraform init (use backend from code)
        run: terraform init -reconfigure

      - name: Select workspace (default)
        run: terraform workspace select default || terraform workspace new default

      - name: Plan destroy
        run: terraform plan -destroy -no-color -input=false -out=destroy.tfplan

      - name: Apply destroy
        run: terraform apply -input=false -auto
