name: Vprofile IAC

on:
  push:
    branches: [main, stage]
    paths: ["terraform/**"]
  pull_request:
    branches: [main]
    paths: ["terraform/**"]

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER: vprofile-eks

jobs:
  terraform:
    name: Terraform code change
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    permissions:
      contents: read
      id-token: write  # (harmless now; useful if you later switch to OIDC)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1        # your config allows 1.x (>=1.6.3)
          terraform_wrapper: false

      - name: Terraform Init (use backend from code)
        run: terraform init -reconfigure
        # If you *must* override the bucket, sanitize it to avoid trailing-space bugs:
        # run: |
        #   terraform init -reconfigure \
        #     -backend-config="bucket=$(printf '%s' '${{ secrets.BUCKET_TF_STATE }}' | xargs)" \
        #     -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Format
        run: terraform fmt -recursive -check -diff

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -out=planfile

      - name: Upload planfile (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan
          path: terraform/planfile

      - name: Terraform Apply (main only)
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -input=false -auto-approve -parallelism=1 planfile

      - name: Update kubeconfig
        id: config
        if: github.ref == 'refs/heads/main' && steps.apply.outcome == 'success'
        run: aws eks update-kubeconfig --name "$EKS_CLUSTER" --region "$AWS_REGION"

      - name: Install Ingress controller
        if: github.ref == 'refs/heads/main' && steps.config.outcome == 'success'
        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/aws/deploy.yaml
